name: Changelog

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "**/CHANGELOG.md"

jobs:
  if_merged:
    # This job will only run if the PR is merged and head branch is changeset-release/main
    if:
      ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'changeset-release/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Update changelog
        run: |
          pnpm changelog --number={{ github.event.pull_request.number }}
          git add .
          git commit -m "chore: update changelog"
          git push origin main
