name: Changelog

on:
  pull_request:
    branches:
      - changeset-release/main
    types: [synchronize, opened]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Update changelog
        run: |
          pnpm changelog --number=${{ github.event.pull_request.number }}
          git add .
          git commit -m "chore: update changelog"
          git push
