name: Publish to NPM

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        name: Load Yarn cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Setup CI Git User
        run: |
          git config --global user.email "joseshegs@gmail.com"
          git config --global user.name "Sage"

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish packages
        uses: changesets/action@master
        with:
          publish: yarn release
          commit: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
