name: Publish to NPM

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Setup CI Git User
        run: |
          git config --global user.email "joseshegs@gmail.com"
          git config --global user.name "Segun Adebayo"

      - name: Configure npm
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: "ci(changesets): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Release to dev tag
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          yarn changeset version --snapshot dev
          yarn changeset publish --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dispatch update to docs
        if: steps.changesets.outputs.published == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SAGE_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'chakra-ui',
              repo: 'zag-docs',
              workflow_id: 'deps.yml',
              ref: 'main'
            })
