name: Add Visualizer Link

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Visualizer link
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Visualizer can be found [here](https://state-machine-viz.vercel.app/pr/${{ github.event.number }}) :confetti_ball:
          comment_includes: "Visualizer can be found"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
